#!/bin/bash
if [ "$1" == "train" ]; then
   if [ "$2" == "gdb" ]; then
      gdb --args ./train 5 ./model_init.txt ./data/train_seq_01.txt ./model_01.txt
   else
      ./train 100 ./model_init.txt ./data/train_seq_01.txt ./model_01.txt
      ./train 100 ./model_init.txt ./data/train_seq_02.txt ./model_02.txt
      ./train 100 ./model_init.txt ./data/train_seq_03.txt ./model_03.txt
      ./train 100 ./model_init.txt ./data/train_seq_04.txt ./model_04.txt
      ./train 100 ./model_init.txt ./data/train_seq_05.txt ./model_05.txt
   fi
elif [ "$1" == "test" ]; then
   if [ "$2" == "gdb" ]; then
      gdb --args ./test ./modellist.txt ./data/test_seq.txt ./result.txt
   else
      ./test ./modellist.txt ./data/test_seq.txt ./result.txt
   fi
fi
